// ---------------------------
// This file was generated by Nango (v0.69.45)
// You can version this file
// ---------------------------

/**
 * ! ** DEPRECATION NOTICE **
 * ! This file will stop being generated in future versions of nango.
 * ! For access to function types, please export types directly from your code.
 * ! You can leverage `zod.infer` to generate types from your zod schemas.
 * ! See the official zod documentation: https://zod.dev/basics?id=inferring-types
 */

export interface GithubIssue {
  id: string;
  owner: string;
  repo: string;
  issue_number: number;
  title: string;
  state: string;
  author: string;
  author_id: number;
  body: string;
  date_created: string;
  date_last_modified: string;
};

export type SyncMetadata_github_fetchIssues = void

export interface ActionInput_github_createIssue {
  id: string;
  owner: string;
  repo: string;
  issue_number: number;
  title: string;
  state: string;
  author: string;
  author_id: number;
  body: string;
  date_created: string;
  date_last_modified: string;
};

export type ActionOutput_github_createIssue = void
