#!/usr/bin/env tsx
/**
 * generate-secrets-md -- derive .github/SECRETS.md from actual SDK imports.
 *
 * Scans `lib/` and `app/` for vendor SDK imports and writes a checklist of
 * every GitHub Actions secret the project needs. The goal: when you
 * onboard the project to CI you have one file that tells you exactly
 * which secrets to add and where they're used.
 *
 * Run: `pnpm secrets:check`
 *
 * Output: `.github/SECRETS.md` -- safe to commit (no secret values).
 */

import { readdirSync, readFileSync, statSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

interface VendorSpec {
  label: string;
  imports: string[];
  envKeys: string[];
  jobs: string[];
  url: string;
}

const VENDORS: VendorSpec[] = [
  {
    label: 'AssemblyAI',
    imports: ['assemblyai'],
    envKeys: ['ASSEMBLYAI_API_KEY'],
    jobs: ['live-integrations', 'api-smoke'],
    url: 'https://www.assemblyai.com/app',
  },
  {
    label: 'Firecrawl',
    imports: ['@mendable/firecrawl-js'],
    envKeys: ['FIRECRAWL_API_KEY'],
    jobs: ['live-integrations', 'research-refresh'],
    url: 'https://firecrawl.dev/app',
  },
  {
    label: 'Deepgram',
    imports: ['@deepgram/sdk'],
    envKeys: ['DEEPGRAM_API_KEY'],
    jobs: ['live-integrations'],
    url: 'https://console.deepgram.com',
  },
  {
    label: 'OpenAI',
    imports: ['openai', '@ai-sdk/openai'],
    envKeys: ['OPENAI_API_KEY'],
    jobs: ['ai-evals', 'e2e'],
    url: 'https://platform.openai.com/api-keys',
  },
  {
    label: 'Anthropic',
    imports: ['@anthropic-ai/sdk', '@ai-sdk/anthropic'],
    envKeys: ['ANTHROPIC_API_KEY'],
    jobs: ['ai-evals', 'ai-browser'],
    url: 'https://console.anthropic.com/settings/keys',
  },
  {
    label: 'Google AI',
    imports: ['@google/generative-ai', '@ai-sdk/google'],
    envKeys: ['GOOGLE_GENERATIVE_AI_API_KEY'],
    jobs: ['ai-evals'],
    url: 'https://aistudio.google.com/app/apikey',
  },
  {
    label: 'Supabase',
    imports: ['@supabase/supabase-js'],
    envKeys: ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY', 'SUPABASE_ANON_KEY'],
    jobs: ['e2e', 'api-smoke'],
    url: 'https://supabase.com/dashboard/project/_/settings/api',
  },
  {
    label: 'Langfuse',
    imports: ['langfuse', '@langfuse/otel'],
    envKeys: ['LANGFUSE_PUBLIC_KEY', 'LANGFUSE_SECRET_KEY'],
    jobs: ['tests', 'e2e'],
    url: 'https://cloud.langfuse.com/settings',
  },
  {
    label: 'Vercel AI Gateway',
    imports: ['@ai-sdk/gateway'],
    envKeys: ['AI_GATEWAY_API_KEY'],
    jobs: ['ai-evals'],
    url: 'https://vercel.com/dashboard/integrations/ai-gateway',
  },
  {
    label: 'Stripe',
    imports: ['stripe'],
    envKeys: ['STRIPE_SECRET_KEY'],
    jobs: ['e2e'],
    url: 'https://dashboard.stripe.com/apikeys',
  },
];

const IGNORE_DIRS = new Set(['node_modules', '.next', '.git', 'dist', 'build', 'coverage']);

function walk(dir: string, out: string[] = []): string[] {
  try {
    for (const entry of readdirSync(dir)) {
      if (IGNORE_DIRS.has(entry)) continue;
      const full = join(dir, entry);
      const stat = statSync(full);
      if (stat.isDirectory()) walk(full, out);
      else if (/\.(ts|tsx|js|jsx|mjs)$/.test(entry)) out.push(full);
    }
  } catch { /* unreadable dir -- skip */ }
  return out;
}

function main(): void {
  const cwd = process.cwd();
  const files = [...walk(join(cwd, 'lib')), ...walk(join(cwd, 'app'))];

  const detected: VendorSpec[] = [];
  for (const vendor of VENDORS) {
    const re = new RegExp(`from\\s+['"\`](?:${vendor.imports.map(i => i.replace(/[.*+?^${}()|[\\]/g, '\\$&')).join('|')})['"\`]`);
    if (files.some(f => re.test(readFileSync(f, 'utf-8')))) {
      detected.push(vendor);
    }
  }

  const lines: string[] = [
    '# Required GitHub Actions Secrets',
    '',
    '> This file is generated by `pnpm secrets:check` -- do not edit by hand.',
    '> Re-run whenever you add or remove an SDK import.',
    '',
    'Each secret below is required by at least one vendor SDK currently imported in `lib/` or `app/`.',
    'Add them at: `Settings → Secrets and variables → Actions` in your GitHub repository.',
    '',
  ];

  if (detected.length === 0) {
    lines.push('_No external vendor SDKs detected. No secrets required yet._');
  } else {
    lines.push('| Vendor | Env Vars | Used By Jobs | Create Key |');
    lines.push('|--------|----------|--------------|------------|');
    for (const v of detected) {
      lines.push(
        `| ${v.label} | ${v.envKeys.map(k => `\`${k}\``).join('<br/>')} | ${v.jobs.map(j => `\`${j}\``).join(', ')} | [console](${v.url}) |`,
      );
    }
    lines.push('');
    lines.push('## Why these are needed');
    lines.push('');
    lines.push('- **Live integration tests** use `it.skipIf(!process.env.KEY)` so missing secrets skip cleanly -- tests pass but do not actually verify anything.');
    lines.push('- **API route smoke tests** require real backends for any route that calls a vendor. Missing keys surface as a 500 in `tests/api/route-smoke.test.ts`, caught by CI.');
    lines.push('- **Nightly runs** exercise every vendor; if a vendor breaks their API at 3am, the job fails by 6am.');
  }

  lines.push('');
  lines.push('_Last generated: ' + new Date().toISOString() + '_');

  const outDir = join(cwd, '.github');
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, 'SECRETS.md'), lines.join('\n') + '\n', 'utf-8');
  process.stdout.write(`Wrote .github/SECRETS.md (${detected.length} vendor${detected.length === 1 ? '' : 's'} detected)\n`);
}

main();
